runtime: python37 # or another supported version

instance_class: F1

env_variables:
  MYSQL_USER: 'root' # please put in your credentials
  MYSQL_PASSWORD: sql.1234 # please put in your credentials
  MYSQL_DB: flight_guru # please put in your credentials
  MYSQL_HOST: '34.69.10.63' # please put in your credentials
  

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles